# Generated by Django 6.0.4 on 2026-05-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_principal_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
