# Generated by Django 6.0.4 on 2026-06-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_blueprint'),
        ('users', '0005_institution_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='users.institution'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='users.institution'),
        ),
    ]
