# Generated by Django 6.0.4 on 2026-06-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_blueprint_institution_questionpaper_institution'),
        ('users', '0005_institution_alter_userprofile_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_hod', 'Pending HOD Approval'), ('pending_controller', 'Pending Exam Controller Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hod_remarks', models.TextField(blank=True, null=True)),
                ('controller_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('controller_remarks', models.TextField(blank=True, null=True)),
                ('controller_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller_approvals', to=settings.AUTH_USER_MODEL)),
                ('hod_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approvals', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='users.institution')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='papers.questionpaper')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('approval_submitted', 'Paper Submitted for Approval'), ('approval_approved', 'Paper Approved'), ('approval_rejected', 'Paper Rejected'), ('info', 'General Info')], default='info', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.questionpaper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
