# Generated by Django 6.0.4 on 2026-05-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_is_deleted_question_sub_topic_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
