# Generated by Django 6.0.4 on 2026-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('Remember', 'Remember'), ('Understand', 'Understand'), ('Apply', 'Apply'), ('Analyze', 'Analyze'), ('Evaluate', 'Evaluate'), ('Create', 'Create')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='co_mapping',
            field=models.CharField(blank=True, help_text='Course Outcome (e.g. CO1, CO2)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='po_mapping',
            field=models.CharField(blank=True, help_text='Program Outcomes (comma separated)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.IntegerField(blank=True, help_text='Unit number (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
