# Generated by Django 6.0.4 on 2026-06-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_bloom_level_question_co_mapping_and_more'),
        ('users', '0005_institution_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.institution'),
        ),
    ]
